---
title: "Week 1: Programming in Python"
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

---

## Day 1 


* Colab notebooks
  * [Introduction to Python - Part 1](https://colab.research.google.com/drive/1cXO-n8fnLDH2zdYMLWcD4wDap3q2RwEO?usp=sharing)
  * [Python Part 1 Exercises](https://colab.research.google.com/drive/1YmBhVIz44JaT5KmcA_0xCSOBXbdojPyc?usp=sharing)
  * [Python Part 1 Exercise Solutions](https://colab.research.google.com/drive/1-CqD0EU14uemonqM1aLLK-eX8Ur_gNmk?usp=sharing)

* Sections
  * Setting Up Colab
  * Python Basics
  * Comparators and Conditionals
  * Data Structures (Lists, Tuples, Dictionaries, Sets)

* Recordings
  * Day 1 recordings can be viewed [here](https://harvard.zoom.us/rec/share/OORtyaUPqd8Gn8jR_6cEkksg3ykkUHMCBYW868h-YTpIlTGPWJCZ5q1gtCBsLGM.Rmja82fi5x_tjtjt)
  
  


<br>

## Day 2 and Day 3

* Colab notebooks
  * [Introduction to Python - Part 2](https://colab.research.google.com/drive/1N7sK4qA63UM-L3P8zoK4BaZqwABej8Xi?usp=sharing) 
  * [Python Part 2 Exercises](https://colab.research.google.com/drive/1oYyENE4h0xBCmUMTt3_Bzj3_9CtBLBA-?usp=sharing)
  * [Python Part 2 Exercise Solutions](https://colab.research.google.com/drive/1UUU5dRVtZ5r1uv7P7MJ6Q6JmIsqXSbvO?usp=sharing)

* Sections
   * Functions
   * While Loops 
   * For Loops + Range
   * More on Data Structures
   * Exceptions 
   
* Recordings
  * Day 2 recording can be viewed [here](https://harvard.zoom.us/rec/share/Xuei_m8H2nmfvy9BUBZ1WFiw-6ACnOW-HuEbF-5tQgAutUFgjj0KUHh9P2DH3NNN.akxtWf8NKtuaKxeO)
  * Day 3 recording can be viewed [here](https://harvard.zoom.us/rec/share/4rjc1CmQ32izpJihSZvUj7S8vgsv1nDHrIgRXSJfypyNf0ft0zmiDi6HgZCc3sH-.izeqXaxbs7AuWxQz)

<br>

## Day 4

* Colab notebooks
  * [Introduction to Python - Part 3](https://colab.research.google.com/drive/1vPDXXMQtPedLmxHTKmWkNinjtQACK2NT?usp=sharing) 
  * [Python Part 3 Exercises](https://colab.research.google.com/drive/198D70rNUXLmGx4A0cLpmW66oOY48TKMn?usp=sharing)
  * [Python Part 3 Exercise Solutions]()

* Sections
  * Intro to NumPy
  * Working with Libraries
  * Modules and Packages

* Recordings
  * Day 4 recordings can be viewed [here](https://harvard.zoom.us/rec/share/TFcNg_lyeJglOoaOEAPavg7WUVNpjcxluFyraCCtF4WoM8aOxZosEtcRfETOx1hp.png-yZWMGyx-SA5b)
<br>

## Day 5

* Colab notebooks
  * [Introduction to Python - Part 4](https://colab.research.google.com/drive/1QgHqcXa91VafW8abrntKGMETiWQSlARu?usp=sharing) 
  * [Python Part 4 Exercises](https://colab.research.google.com/drive/1mOuBtpD0bRpN2IvlRoe0mE1NLbKpbt3J?usp=sharing)
  * [Python Part 4 Exercise Solutions]()

* Sections
  * Intro to Matplotlib
  * Coding on Raspberry Pi

<br>





